<a href="https://colab.research.google.com/github/pagarsky/nn2022/blob/master/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Лабораторна робота №2
### з дисципліни "Нейронні мережі"
### студента групи КН-31/2
### Пагарського Олексія
#### Варіант №7

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn import datasets as ds

from google.colab import drive

### За матеріалами [2] ознайомитись із засадами бібліотеки TensorFlow:
- засвоєння поняття тензору
- знати різні способи створення тензорів
- створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)
- продемонструвати основні математичні операції над тензорами
- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)


In [ ]:
c = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
d = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
print(tf.matmul(c, d))
print(tf.Variable([10, 7]))

tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>


In [ ]:
r = tf.random.Generator.from_seed(42).normal(shape=(3, 2))
r

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
print(r.shape, r.ndim, tf.size(r))

(3, 2) 2 tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
print(r[:, 1])

tf.Tensor([-0.06854702 -1.2573844  -1.8107855 ], shape=(3,), dtype=float32)


In [ ]:
print(
    r + 10,
    r * 10,
    tf.matmul(r, tf.zeros([2, 3])),
    r @ tf.zeros([2, 3])
)

tf.Tensor(
[[ 9.24342   9.931453]
 [10.075951  8.742616]
 [ 9.768063  8.189215]], shape=(3, 2), dtype=float32) tf.Tensor(
[[ -7.565803    -0.68547016]
 [  0.7595026  -12.573844  ]
 [ -2.3193762  -18.107855  ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
tf.reshape(r, [1, 6])

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ]], dtype=float32)>

### 🛠 Упражнения

#### Создайте вектор, скаляр, матрицу и тензор со значениями по вашему выбору, используя tf.constant().

In [ ]:
scalar = tf.constant(1)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [3, 2, 1]])
tensor = tf.constant([[[1, 1]],
                      [[1, 1]],
                      [[1, 1]]])

#### Найдите форму, ранг и размер тензоров, которые вы создали в 1.

In [ ]:
print(scalar.shape, scalar.ndim, tf.size(scalar))
print(vector.shape, vector.ndim, tf.size(vector))
print(matrix.shape, matrix.ndim, tf.size(matrix))
print(tensor.shape, tensor.ndim, tf.size(tensor))

() 0 tf.Tensor(1, shape=(), dtype=int32)
(3,) 1 tf.Tensor(3, shape=(), dtype=int32)
(2, 3) 2 tf.Tensor(6, shape=(), dtype=int32)
(3, 1, 2) 3 tf.Tensor(6, shape=(), dtype=int32)


#### Создайте два тензора, содержащие случайные значения между 0 и 1 с shape [5, 300].
#### Умножьте два тензора, которые вы создали в 3, используя матричное умножение.
#### Умножьте два тензора, которые вы создали в 3, используя скалярное произведение.


In [ ]:
a = tf.random.normal(shape=[5, 300])
b = tf.random.normal(shape=[5, 300])

print(a @ tf.transpose(b))
print(a * b)

tf.Tensor(
[[  0.8935814  21.7817    -23.67244   -12.153208   13.83876  ]
 [ 24.873507  -18.080126   11.683866  -13.786795    4.990341 ]
 [ 23.2695     27.305506  -14.486826    1.8113613  17.878836 ]
 [ 20.9744     22.129208  -12.139207  -14.320183    1.7330227]
 [-37.995804  -23.505503  -17.34692   -13.403022  -21.200909 ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[ 1.2200252e-01  1.8741040e-03 -5.2181333e-01 ...  5.6880790e-01
  -5.8390725e-01 -1.5962036e-01]
 [ 5.6254469e-02 -9.1312461e-02  2.0329783e+00 ... -2.3435531e-02
  -1.6131230e-01  9.7783215e-02]
 [-1.6470024e-02  3.1697876e+00  2.6228487e-01 ...  6.0709023e-01
   1.3724351e+00 -4.2932967e-04]
 [-5.2056085e-02 -1.7219387e+00  4.6748048e-01 ... -2.6400718e-03
  -1.8601693e-01  3.8730425e-01]
 [ 3.1866452e-01 -3.3497453e-01 -3.0042908e-01 ...  3.5969648e-01
  -5.1179659e-01 -1.8890382e-01]], shape=(5, 300), dtype=float32)


#### Создайте тензор со случайными значениями между 0 и 1 с помощью shape [224, 224, 3].
#### Найдите минимальное и максимальное значения тензора, который вы создали в 6.
#### Создал тензор со случайными значениями формы, [1, 224, 224, 3]затем сжал его, чтобы изменить форму на [224, 224, 3].

In [ ]:
rand = tf.random.normal(shape=[224, 224, 3])
tf.reduce_max(rand)
tf.reduce_min(rand)

n = tf.random.normal(shape=[1, 224, 224, 3])
print(tf.squeeze(n).shape)

(224, 224, 3)


#### Горячее кодирование тензора, созданного в 9.

In [ ]:
categories = [0, 1, 2, 3]
tf.one_hot(categories, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Висновок
В результаті виконання лабораторної роботи ми ознайомилися з структурою даних Тензор, навчилися створювати, модифікувати та працювати з ними.